# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa6d48a50f9a32efec9ca9e96d3b4fb1b85e65b102acb69a55ae83aaabc4cf723f0a0a2f10d7a54ba4d74333c481daa2899d84388a2c261e1880b992bc3d6558

test:
  secret_key_base: f360fe3fa6e8877b0752e6295c97e80b32f9c3622466deb45c5851e071c7cd981c6e68cd13b0e14905bb53062d593596370bf83269a51e6e67788ea0d4ee7495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
